---
title: "Life Without Parole Prisoner Organ Donations"
author: "Kahlil W. Ethan T. Owen. D."
date: "11/13/2019"
output: 
  pdf_document:
    toc: true
    number_sections: true
---
\fontsize{12}{22}
\selectfont

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Notes
- Some of the estimates we are using are from 2009, not so confident we've done a good job adjusting for the change in the value of money (is has to be more complicated than an online inflation calculator). So why bother calculating all of them when unsure of how to properly do that. 
- How do I get dollar signs to look normal without a \ @kahlil
- Not all patients who lack a donor are going to pay for dialysis until they die. There may be a better way to quantify the value per QALY lost due to organ shortage. 

# *Abstract* {-}
*The aim of the study is determining whether kidneys of inmates that are serving life without parole (LWOP) or death row inmates have untapped net value to society. The life savings of decreasing transplant waitlist patients may offset the cost of the transplant operation itself, as well as any social costs of an involuntary program. Perhaps even a voluntary one.*

\break

# Importance

There is a global shortage of organs. The most common transplant being kidneys. Many people who could continue to live healthy normal lives if given kidneys are often placed on long waiting lists for organs. Organs legally can't be sold or bought anywhere, except Iran, and **must** be donated. By increasing the supply of organs without any cost to functioning society we could potentially see life savings in the hundreds of millions.


# Proposition

## Baseline

As with any benefit-cost analysis, we will consider a $Net\ Benefits = 0$. We could calculate and quantify the cost of life of the status quo as it relates to people dying on transplant wait-lists. However, it would just work into the primary proposal and cancel out. 

## Primary Proposal

All LWOP and Death Row inmates are involuntarily marked as kidney donors upon their death. Their kidneys are then made available to patients on a waiting list.

## Secondary Proposal

Similar to the first proposal, but the system is voluntary with an incentive. 

\break

# Technical Plan

## Assumptions

1. The probability of a *prison kidney* being usable can be substituted 
2. The survey methodology is sound
3. There is no corruption in the prison system
4. If a patient in need of a life-saving organ were to decline it due to its origin, another patient further down the line in need of a transplant would accept it. Therefore, we will value prisoner kidneys the same as non-prisoner kidneys.
5. Facility and staffing costs will be ignored


## Monetization of Benefits and Costs

|Symbol|Benefit|Cost|
|---|---|---|
|$\phi$| Life Savings* |   |
|$\gamma$|   |Transplant Operation*|
|$\rho$|   | Social Cost to Prisoners*|
$$\*_{*defined\ below}$$

### Life Savings $\phi$
Description: The monetary value provided in life savings due to an increase in usable kidney supply. The calculation is relative to the 

Assumptions:
- *All transplants are successful* (find rates please)
- Each patient who is offered a transplant due to the increase in kidney supply would have otherwise paid for dialysis until death. 
- Patients who get a kidney transplant before dialysis generally live 10-15 years longer, from which we assume the average is 12.5 years (value from Beth Israel Deaconess Medical Center). 

$$ Life\ Savings\ Benefit = \widehat{LAT} * \widehat{\Delta T} * D_s * p(U_k) $$

$\widehat{LAT}$: Average number of years of healthy life after a successful transplant
= 12.5

$\hat{\Delta T}$: Change (*increase*) in kidney supply. Number of LWOP and Death Row inmates that die annually multiplied by two, since each person has two donable kidneys. 
= 162.4

#### Renal Dialysis Standard $D_s$
The Renal Dialysis Standard is a measure of the value of a statistical year of life implied by dialysis practice, which averages $129,090 per Quality-Adjusted Life Year (QALY) according to (Lee, 2009)[^1], equal to \$154,503 after adjusting for inflation[^2]. The number is an estimate of the financial value of dialysis compared to no treatment, representing an increase in lifetime and quality of life. The lee paper takes into account life expectancy to calculate and estimate for the mean lifetime cost of dialysis per person, equal to \$337,085 (\$281,640 before adjusting for inflation) 

[^1]: https://www.valueinhealthjournal.com/article/S1098-3015(10)60676-6/pdf?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1098301510606766%3Fshowall%3Dtrue
[^2]: https://westegg.com/inflation/

#### Estimate

$$  (162.4 * (1-0.246) * 129,000 * 12.5) = 197,449,980 $$

24.6% of prisoners are not viable donors based on this paper. Conservatively.
https://www.bjs.gov/content/pub/pdf/mpsfpji1112.pdf

### Transplant Operation Cost $\gamma$
Description: The cost of completing an operation. Kidneys cannot be sold or bought, but typically the recipient pays for all the medical operations. 

#### Estimate

This is an estimate for the increase in consumer surplus due to the provided kidneys (is this actually a measure of CS?). It assumes that the cost of transplant will not change due to the additional 162 supplied kidneys. 

$$414,000 * 81 * 2 = 67,068,000$$

$414,800 for a single kidney transplant.
Based on the 2017 Milliman Report.

### Reduction in cost to consumers

Assuming:
- The policy allows for 162 successful kidney transplants
- In all cases the alternative would have been 10 years of dialysis at a cost of $129,000
- The aggregate cost of the operations to consumers (as calculatd above) will be  $67,068,000

$$129,000 * 162 * 10 - 67,068,000 = 141,912,000$$

### Social Cost $\rho$
Description: Cost to society in USD for involuntarily harvesting deceased prisoner’s organs without their consent. 

$$Social\ Cost = \widehat{p(C)} * \bar{A_m} * \widehat{I_c} $$

$\widehat{p(C)}$: Number of people who would need to have their next of kin compensated for having their kidneys used.

$\bar{A_m}$: Average compensation amount.

$\widehat{I_c}$: Number of LWOP and Death Row inmates that die in prison annually.

#### Estimate

$$  ((0.11*(0.25)) * 57,290) * 34,000 = 49,826,150 $$

*Footnote:* The probabilities and compensation amounts are calculated on a team authored survey that was sent out to a small sample of people. As the assumption states, we are assuming our methodology is sound. We know it more than likely isn't and the sample is too small to make any real claims about, but we are working on improving the quality of feedback.

### Calculating Net Benefits (NB)

$$ NB = \phi - \gamma - \rho$$

#### Estimate

Assuming that prisoners have standing:
$$157,959,984 -  49,826,150 - 33,534,000 = 74,599,834$$

Assuming that prisoners do not have standing:
$$157,959,984 - 33,534,000 = 124,425,984$$

### Discounting 

Assuming that that organs have a relatively high demand elasticity and don't have a direct biological value we don't think discounting them is appropriate. If anything, they are already discounted based on survival rates and healthy years post-op based on the papers we are sourcing our data from.

The other point that could be considered for discounting is adjusting the compensation number for inflation. However, we are considering the project on a year-by-year basis and don't think the increase will be drastic enough to warrant consideration.

# Data
*Still working on ensuring our data is sound and the numbers make sense in scope of our analysis. We feel that the required data is clearly listed and is attainable in a reasonable amount of time*

# Sources
Bentley, T. S. (2017). 2017 U.S. organ and tissue transplant cost estimates and discussion. Milliman Research Report. Retrieved from http://www.milliman.com/uploadedFiles/insight/2017/2017-Transplant-Report.pdf
Kidney Transplant. (2018). Retrieved from https://www.bidmc.org/centers-and-departments/transplant-institute/kidney-transplant
Lee, C.P. (2009) An Empiric Estimate of the Value of Life: Updating the ... Retrieved from https://onlinelibrary.wiley.com/doi/full/10.1111/j.1524-4733.2008.00401.x.

# Work to be completed

1. Finding numbers |  DONE
2. Summarising and analysing survey data | DONE
3. Proper citation
4. Listing contingencies.
5. Finish the write up

